# SITE SETTINGS
title: Oslosessions
# email: eplehans@gmail.com
# description: Site description
# author: Hans Kristian Smedsrød
baseurl: ""
url: "http://www.oslosessions.no/" # the base hostname & protocol for your site
permalink: :title/
canonical: "http://www.oslosessions.no/"

# External usernames
# facebook_username: oslosessions
# instagram_username: oslosessions

disqus: oslosessions
google_analytics: UA-56557241-1

# BUILD SETTINGS
markdown: kramdown

#Page and post defaults
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      published: "true"

prose:
  siteurl: "http://oslosessions.no/"
  media: "media"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title 1"
      - name: "vimeoCode"
        field:
          label: "Vimeo code"
          help: "The last digits in the vimeo video link"
          element: "text"
          type: "text"
          placeholder: "111721083"
      - name: "posterImg"
        field:
          label: "Poster image"
          help: "Main background picture from the event"
          element: "text"
          type: "text"
          placeholder: "Url to your awesome image"