# SITE SETTINGS
title: Oslo Sessions
description: Oslo Sessions loves live music. We've got the bouncing beats and sweet tunes from your favourite artists.
baseurl: ""
url: "http://www.oslosessions.no/" # the base hostname & protocol for your site
disclaimer: This service is provided by Oslo Sessions. The music is distributed with permission from TONO. Unauthorised usage or copying is illegal.
permalink: :title/
canonical: "http://www.oslosessions.com/"

# External usernames
facebook_username: oslosessions
instagram_username: oslosessions
soundcloud_username: oslosessions

# Emails
email: mail@oslosessions.com
booking_email: booking@oslosessions.com

#google_analytics: UA-57922199-1
google_analytics: UA-61996198-1


# BUILD SETTINGS
markdown: kramdown

defaults:
  -
    values:
      layout: "post"

# PROSE SETTINGS
prose:
  siteurl: "http://www.oslosessions.com/"
  media: "media"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "vimeoCode"
        field:
          label: "Vimeo video id"
          help: "The last digits in the vimeo video link"
          element: "text"
          type: "text"
          placeholder: "Vimeo video id"
      - name: "imgurId"
        field:
          label: "The digits in the imgur image file"
          help: "Main background picture from the event"
          element: "text"
          type: "text"
          placeholder: "Id to your awesome image"