# SITE SETTINGS
title: Oslo Sessions
description: Oslo Sessions
baseurl: ""
url: "http://www.oslosessions.no/" # the base hostname & protocol for your site
disclaimer: Denne tjenesten tilbys av Oslo Sessions. Musikken er gjengitt med tillatelse fra TONO. Uautorisert fremføring eller kopiering er ulovlig
permalink: :title/
canonical: "http://www.oslosessions.com/"

# External usernames
facebook_username: oslosessions
instagram_username: oslosessions
soundcloud_username: oslosessions

# Emails
email: mail@oslosessions.com
booking_email: booking@oslosessions.com

google_analytics: UA-57922199-1

# BUILD SETTINGS
markdown: kramdown

# PROSE SETTINGS
prose:
  siteurl: "http://www.oslosessions.com/"
  media: "media"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "vimeoCode"
        field:
          label: "Vimeo code"
          help: "The last digits in the vimeo video link"
          element: "text"
          type: "text"
          placeholder: "111721083"
      - name: "posterImg"
        field:
          label: "Poster image"
          help: "Main background picture from the event"
          element: "text"
          type: "text"
          placeholder: "Url to your awesome image"